### ISSUE TITLE
Nexus Security Bulletin—November 2015

### ISSUE THREAD

**Issue by cryptix** [ucam-cl-dtg/android-vulnerabilities#1]
https://groups.google.com/forum/#!topic/android-security-updates/GwZn7sixask

The mediaserver and libstagefright vulnerabilities seem to be quite grave.

**Comment by drt24** [comment]
I am hoping to shortly have a few days while some code runs to work on this and then I will add all the vulnerabilities. Sometime next week anyway.

**Comment by drt24** [comment]
Now fixed in recent updates. Nearly 4 years later rather than "next week" as originally stated.
