### ISSUE TITLE
Website build failure missing graphs file

### ISSUE THREAD

**Issue by drt24** [ucam-cl-dtg/android-vulnerabilities#9]
remote: processing: jcase.json
    remote: processing: kg365.json
    remote: processing: dcc52.json
    remote: Traceback (most recent call last):
    remote:   File "/societies/androidvulns/poole/poole.py", line 733, in <module>
    remote:     main()
    remote:   File "/societies/androidvulns/poole/poole.py", line 727, in main
    remote:     build(opts.project, opts)
    remote:   File "/societies/androidvulns/poole/poole.py", line 590, in build
    remote:     macros[fn]()
    remote:   File "./macros.py", line 811, in hook_preconvert_stats
    remote:     month_graphs(months_range(first_date, last_date))
    remote:   File "./macros.py", line 838, in month_graphs
    remote:     with open(filename, 'w') as graph_file:
    remote: FileNotFoundError: [Errno 2] No such file or directory: 'graphs/graph-2009-09.gv'

**Comment by danielchriscarter** [comment]
Should be OK now - just needed a placeholder in the graphs directory so that the directory itself gets uploaded
